import { VerticalBox, ListView, HorizontalBox , Button} from "std-widgets.slint";

component RssArticle inherits Rectangle {
    in property <string> title;

    width: 320px;
    height: 25px;

    Text {
        text: title;
    }
}

export component RssPage inherits VerticalBox {
    in property <[string]> titles;

    width: 320px;
    height: 240px;

    // callback button_clicked;
    // Button {
    //     text: "hello";
    //     clicked => { root.button_clicked(); }
    // }

    ListView {
        for article_title in root.titles: article_titles := RssArticle {
            title: article_title;
        }
    }
}
